name: Bot Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *' # بيعيد تشغيل نفسه كل 4 ساعات لضمان الاستمرار

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install discord.py

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python bot.py
